server:
  port: 8080
  error:
    whitelabel:
      enabled: false
    include-message: always

spring:
  datasource:
    url: jdbc:mysql://database-1.cp0iwyyukgsv.ap-northeast-2.rds.amazonaws.com:3306/gdsc?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&&zeroDateTimeBehavior=convertToNull
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver

  thymeleaf:
    check-template-location: false

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

    logging:
      level:
        org.hibernate.SQL: debug
